Update docs
quintoandar/butterfree pull request #320
Opened 2021-04-29 14:40 UTC by roelschr

## Why? :open_book:
_Replace me for a cool overview of why this PR is being created. You can
refer to the Jira task or Github issue here too. Never forget to put the
tag of a related Jira task in the title._

## What? :wrench:
_Replace me for a detailed explanation of what is being modified._
_Want to add some awesome bullet points?_
- _First changes;_
- _Second changes;_
- _..._

_How about some cool checkboxes?_
- [X] _First changes;_
- [X] _Second changes;_
- [ ] _..._

## Type of change
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Release

## How everything was tested? :straight_ruler:
_Have you achieved all the acceptance criteria? How?_
_Is there any alternative flow in the testing process that you want to describe?_

## Checklist
- [ ] My code follows the style guidelines of this project (docstrings, type hinting and linter compliance);
- [ ] I have performed a self-review of my own code;
- [ ] I have made corresponding changes to the documentation;
- [ ] I have added tests that prove my fix is effective or that my feature works;
- [ ] New and existing unit tests pass locally with my changes;
- [ ] Add labels to distinguish the type of pull request. Available labels are `bug`, `enhancement`, `feature`, and `review`.

## Attention Points :warning:
_Replace me for what the reviewer will need to pay attention to in the PR or just to cover any concerns after the merge._

2021-05-04 21:20 UTC, moromimay requested changes
Some questions and advice: :wink: 

- The `butterfree._cli` module, were you unable to map it? :thinking: 
- Requirements: we have the requirements in the path docs, we can create a make command to install them more easily, WDYT?
- The `cli.md` markdown file, I believe it needs to be referenced in `index.rst` or `home.md`, both to appear in the documentation and to make it easier for users to find the content.
- It would be interesting to put the supported databases in the AutomateMigration documentation, for example: cassandra.

2021-05-04 21:20 UTC, moromimay commented on docs/source/cli.md
> +$~ butterfree help
```suggestion
$~ butterfree --help
```

2021-05-04 21:20 UTC, moromimay commented on docs/source/cli.md
> +For more information, please, check `butterfree migrate apply help` :)
```suggestion
For more information, please, check `butterfree migrate apply --help` :)
```

2021-05-05 19:54 UTC, roelschr commented
> Some questions and advice: 
> 
> * The `butterfree._cli` module, were you unable to map it? :thinking: 

I couldn't find a way to map it, but thinking better about it, does it make sense to show API documentations for a private interface that users shouldn't be using?

> * Requirements: we have the requirements in the path docs, we can create a make command to install them more easily, WDYT?

I guess that they should've been added into our requirements-dev file, that is installed locally for development. This PR does that, and now, it is easily installed by the `make requirements` command.

> * The `cli.md` markdown file, I believe it needs to be referenced in `index.rst` or `home.md`, both to appear in the documentation and to make it easier for users to find the content.

Done! Thanks :smile: 

> * It would be interesting to put the supported databases in the AutomateMigration documentation, for example: cassandra.

Done! Thanks :smile:

2021-05-07 12:20 UTC, moromimay approved these changes

2021-05-07 17:59 UTC, merged